### ISSUE TITLE
App not aware of uninstalls

### ISSUE THREAD

**Issue by flux627** [discolabs/django-shopify-auth#16]
I have localhost routing through ngrok as per the tutorial. I visit the ngrok URL, enter in my test shop ID, submit, and then install the app after redirection.

Then, I uninstall the app from the test shop admin. When I visit the ngrok URL again, the app redirects me to the old app URL, and shopify tells me that the page I'm looking for could not be found.

Is this intended behavior? Is there any way of knowing if a user has uninstalled an app without reacting to a webhook?

**Comment by gavinballard** [comment]
This is an issue with stale sessions - the user's browser still has a session cookie which is valid for a logged in user after installing the application.

Solving this problem is the responsibility of your app, not this package. What I usually do it catch the `app/uninstalled` webhook and remove all sessions associated with that shop (see my Stack Overflow answer [here](http://stackoverflow.com/questions/235950/how-to-lookup-django-session-for-a-particular-user/26097566#26097566) on how to link users and sessions for exactly this purpose).

**Comment by flux627** [comment]
Thanks!

**Comment by embedded1** [comment]
@flux627 did you take Gavin's approach?
It would be great to see your code that handles the uninstall webhook.

Thanks

**Comment by embedded1** [comment]
@gavinballard can you please share the code that does what you wrote above?
it will be a great asset for the whole community!

Thanks for your help.

**Comment by gavinballard** [comment]
@embedded1 Check the Stack Overflow link.
