### ISSUE TITLE
Multiple Store session management

### ISSUE THREAD

**Issue by hironroy** [discolabs/django-shopify-auth#5]
Do you have a recommended way for handling a user that has the Shopify App (eg. `myapp`) installed in **multiple stores**. Once the user authenticates using the oAuth credentials of one store the `myapp` session is maintained even when the second store (via Embed SDK) is accessing `myapp`.

If there isn't a recommended way of handling this, maybe the `login_required` decorator could be modified to support kicking off re-authentication when the current session's shop doesn't match the `shopify_params` shop? Currently, the wrapper begins with

        if request.user.is_authenticated():
            return f(request, *args, **kwargs)

Any suggestions would be greatly appreciated.

**Comment by gavinballard** [comment]
Hey @hironroy, good question!

You're probably right that this is a case that should be handled by the `login_required` decorator. Something along the lines of the `login_again_if_different_shop` action in the [official Rails app](https://github.com/Shopify/shopify_app/blob/697028001f71cf52e47d93749de426a0b3d7cf7d/lib/shopify_app/login_protection.rb#L27-L31).

Happy to accept a PR that works along the same lines as the Rails version; otherwise I'll take a stab at this next chance I get.

**Comment by gavinballard** [comment]
Closing as I don't have time to work on this. Happy to review and accept a PR though.

**Comment by coler-j** [comment]
@hironroy , did you find an approach that worked for this? I am looking into this and will prepare a PR when I solve it.
