### ISSUE TITLE
Will django-shopify-auth support the new session token authentication?

### ISSUE THREAD

**Issue by ziemb** [discolabs/django-shopify-auth#67]
Since the new auth, using session tokens instead of cookies, has been released in July, is it going to be supported in this package?

https://shopify.dev/tutorials/authenticate-your-app-using-session-tokens

**Comment by stlk** [comment]
Hey, yes, it will be supported. We're using it internally and I'm working on adding cookieless auth to this package. I think we'll have something next week.

**Comment by ziemb** [comment]
That's great news. Thanks for letting me know!

**Comment by stlk** [comment]
The PR is now finished. I just need to update tests. It would be really great if you could try if it works for your use-case.

https://github.com/discolabs/django-shopify-auth/blob/feature/cookieless-auth/shopify_auth/cookieless_auth/README.md

**Comment by ziemb** [comment]
Great. I will probably be able to try it out next week. I will give you update afterwards. Cheers

**Comment by ziemb** [comment]
Hi, I needed to modify the middleware a little bit to fit my case, but overall it worked well with my app. I believe you can finalize this PR. Thanks again.

**Comment by stlk** [comment]
> Hi, I needed to modify the middleware a little bit to fit my case, but overall it worked well with my app. I believe you can finalize this PR. Thanks again.

Thanks for the feedback. Could you please share the middleware or reason why did you needed to change it?

**Comment by ziemb** [comment]
Sent you a message on priv.

**Comment by stlk** [comment]
I forgot to describe middleware ordering. Here's the updated docs.

1. Add `cookieless_auth` to `INSTALLED_APPS` and `"shopify_auth.cookieless_auth.middleware.CookielessAuthMiddleware",` middleware after the `"django.contrib.auth.middleware.AuthenticationMiddleware",`.

myproject/settings.py
```python
INSTALLED_APPS = [
    ...
    "cookieless_auth",
    ...
]

MIDDLEWARE = [
    ...
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "shopify_auth.cookieless_auth.middleware.CookielessAuthMiddleware", # This middleware has to be before django.contrib.auth.middleware.AuthenticationMiddleware.
    ...
]
```

The reason I decided to avoid using `auth.authenticate` and `auth.login` is that it assumes persistent session. Basically "django.contrib.auth.middleware.AuthenticationMiddleware" is there just for the Django admin.

**Comment by aprams** [comment]
As I did minor rewriting of the current session token state a few days ago for our application: what is the reason to use a new Middleware instead of registering as a new AuthenticationBackend in the AuthenticationMiddleware provided by Django? 
I felt this would be more Django-y overall.

**Comment by stlk** [comment]
@aprams That's very interesting. I tried to implement this as a Backend but I just couldn't make it work. From what I saw and experienced Django auth [assumes there's a persistent session](https://github.com/django/django/blob/a2d5ea626ec6aa4eab6b018c4bce58cb27e20676/django/contrib/auth/__init__.py#L169). https://github.com/webstack/django-jwt-auth package uses similar approach as I did.

Could you please share bits of your implementation, especially Backend, so I can see what I missed? :)

**Comment by aprams** [comment]
Mhh that is interesting, indeed. It's been a few weeks since I implemented it, I remember stumbling across a similar issue. I cannot investigate more today, but I can give you the relevant parts in my code that I used. If that does not work, feel free to ping me and I can have a deeper look.

settings.py:

```
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # Commented out, as described in the django-shopify-auth package
    # "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
```

DRF config:


```
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",  # make all endpoints private
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.user.middleware.CookielessAuthBackend",
        "rest_framework.authentication.SessionAuthentication",
    ],
}
```

CookielessAuthBackend:
The `authenticate(request)` simply calls your new authenticate method that I slightly rewrote to support my use case with the discussed ShopifyUserProfile (in the other PR). I just tried to reuse/reference your feature branch as much as possible so that I can incorporate additional changes easily. When you're done with the changes I'll need some rewriting as well, though.

```
class CookielessAuthBackend(BaseAuthentication):
    def authenticate(self, request, **kwargs):
        user = authenticate(request) # <--- see method below - refactor this when done

        if user:
            request.user = user
            return (user, None)

        return None
```

For reference the authenticate method:

```
def get_hostname(url):
    return urlparse(url).netloc


def authenticate(request):
    jwt_token = request.headers.get("Authorization")

    if not jwt_token:
        return

    striped_jwt_token = re.sub(r"Bearer\s", "", jwt_token)
    should_verify_date = not settings.DEBUG
    try:
        decoded_payload = jwt.decode(
            striped_jwt_token,
            settings.SHOPIFY_APP_API_SECRET,
            algorithms=["HS256"],
            audience=settings.SHOPIFY_APP_API_KEY,
            options={
                "verify_sub": False,
                "verify_nbf": should_verify_date,
                "verify_exp": should_verify_date,
            },
        )

        dest_host = get_hostname(decoded_payload["dest"])
        iss_host = get_hostname(decoded_payload["iss"])

        assert (
            dest_host == iss_host
        ), "'dest' claim host does not match 'iss' claim host"
        assert dest_host, "'dest' claim host not a valid shopify host"

        return get_user_model().objects.get(
            shopify_user_profile__myshopify_domain=dest_host
        )

    except (
        ExpiredSignatureError,
        JWTError,
        JWTClaimsError,
        AssertionError,
        ObjectDoesNotExist,
    ) as e:
        logging.warning(f"Login user failed: {e}.")
```

I do remember the issue with the sessions and the link you posted to the auth backend's source makes me question my code, but yeah, here is my current state, which works fine with django admin and JWTs generated by shopify. (Disclaimer: To make django admin work, you need to make sure not to invalidate the passwords as it is the default in the package IIRC)
Other than that I think there were no additional changes on top of your work. 

Let me know if this works for you, otherwise I'll be glad to help where I can.

**Comment by stlk** [comment]
Ah yes, I completely forgot to describe DRF. Authentication story with DRF is a bit different because it has its own auth layer. From my experience Django Views have to use different middleware. DRF Views use custom authentication class.

https://github.com/discolabs/django-shopify-auth/pull/68/commits/f7b1eb9b08d5be132333690d78122d783b54b434

**Comment by aprams** [comment]
Ahh I see, I was not aware of that, that makes sense. 
Thanks for the update - that was fast! Looks good to me, looking forward to integrate it into our application 👍

**Comment by shashitechno** [comment]
hey guys, it is functional yet @aprams @stlk

**Comment by ilovelinux** [comment]
@shashitechno https://github.com/discolabs/django-shopify-auth/tree/master/shopify_auth/session_tokens
